### ISSUE TITLE
What is carbondate?

### ISSUE THREAD

**Issue by entezarlifedesign** [DeepskyLog/laravel-astronomy-library#48]
I use Carbon::now() for this line:

```
$carbonDate = Carbon::now();
$coords = new GeographicalCoordinates(-70.73330, -29.25);
$astrolib = new AstronomyLibrary($carbonDate, $coords);
```

but give error:

`Argument 1 passed to Symfony\Component\HttpFoundation\Response::setContent() must be of the type string or null, object given, called in D:\xampp\htdocs\rtl\vendor\laravel\framework\src\Illuminate\Http\Response.php on line 65`

**Comment by WimDeMeester** [comment]
Hi @entezarlifedesign 

This is a strange error message... At first sight, it does not look like an error in the laravel-astronomy-library, but somewhere else... 
The following simple example does work for me:

```php
use Carbon\Carbon;
use deepskylog\AstronomyLibrary\Coordinates\GeographicalCoordinates;
use deepskylog\AstronomyLibrary\AstronomyLibrary;

$carbonDate = Carbon::now();
$coords = new GeographicalCoordinates(-70.73330, -29.25);
$astrolib = new AstronomyLibrary($carbonDate, $coords);
```

I tried to execute this example in 

```bash
php artisan tinker
```

Can you also send me the result when running the example in tinker?

**Comment by WimDeMeester** [comment]
I will anyway update the documentation to include the _use_-statement and an example of _$carbonDate_

**Comment by entezarlifedesign** [comment]
Hello from me

I just installed Laravel version 7.
I installed your package.
And run the code again, but it gives the same error.

Anyway, thank you.

Which package did you use yourself?

**Comment by entezarlifedesign** [comment]
> I did the following
> 
> ```shell
> laravel new test
> cd test
> composer require deepskylog/laravel-astronomy-library
> ```
> 
> I do `php artisan tinker` then, and I execute the small script:
> 
> ```
> use Carbon\Carbon;
> use deepskylog\AstronomyLibrary\Coordinates\GeographicalCoordinates;
> use deepskylog\AstronomyLibrary\AstronomyLibrary;
> 
> $carbonDate = Carbon::now();
> $coords = new GeographicalCoordinates(-70.73330, -29.25);
> $astrolib = new AstronomyLibrary($carbonDate, $coords);
> ```
> 
> I don't see any errors.
> 
> Can you tell me which version of php and laravel you have (and which operating system?)

Reinstall carbon, But it still does not work.

windows 10, latest update
laravel 8 and 7 tested
php 7.3 in xampp 3.2.4 64bit

composer updated
node updated

**Comment by WimDeMeester** [comment]
The problem is that this package needs php 7.4.  It is stated in the composer.json file, so I don't understand why the package can be installed at all.

**Comment by entezarlifedesign** [comment]
> The problem is that this package needs php 7.4. It is stated in the composer.json file, so I don't understand why the package can be installed at all.


OMG!
I installed directly from laravel command line and i didn't pay attention to the composer.json file!
Please add recommendation passage top of the page! This is customary!

Thank you.

**Comment by WimDeMeester** [comment]
I was under the impression that the composer.json file would force composer install to check the php version.  I'll adapt the documentation.

**Comment by WimDeMeester** [comment]
Can I ask you @entezarlifedesign why you would want to use laravel-astronomy-library?

**Comment by yosefi** [comment]
> Can I ask you @entezarlifedesign why you would want to use laravel-astronomy-library?


Of course
The most important thing is to calculate the arrival and departure of the moon in the zodiac
(Google Translate :D )
