### ISSUE TITLE
trying to find exact location of moon in the sky based on a date and coordinates

### ISSUE THREAD

**Issue by SaqibZafar** [DeepskyLog/laravel-astronomy-library#85]
Hi , i am trying to calculate the moon's position in the sky based on the following, i do not find a method for this in Moon.php, is it possible to be calculated with this lib?

inputs are 
        $geo_coords = new GeographicalCoordinates(4.86463, 50.83220); //lat,lng
        $moondate   = Carbon::create(1992, 12, 20, 0, 0, 0);

need to find the moon's location on these two inputs

**Comment by WimDeMeester** [comment]
You should be able to do the following:

```php
$moon  = new Moon();
$moon->calculateApparentEquatorialCoordinates($moondate);
// If the correction for the location on earth should be done, use the following method
$heightOfLocation = 555;   // In meters
$moon->calculateEquatorialCoordinates($date, $geo_coords, $heightOfLocation);
```

Does this give you the expected answer?

**Comment by SaqibZafar** [comment]
return [$L, $B, $R];

can you explain these params as to what i am getting in return? thanks

**Comment by WimDeMeester** [comment]
The `calculateEquatorialCoordinates` does only calculate the coordinates.  To get the results, do:
```php
$moon->getEquatorialCoordinates()->getRA()->getCoordinate()
$moon->getEquatorialCoordinates()->getDeclination()->getCoordinate()
```

**Comment by SaqibZafar** [comment]
Thanks a bunch
