### ISSUE TITLE
Strange behavior of Equation of Time on March

### ISSUE THREAD

**Issue by rfahmi89** [DeepskyLog/laravel-astronomy-library#90]
Hello. I'm currently trying to explore this library. It's great! Thank you for working on it and make it available to everyone.

I found the EoT return the invalid value in March. Especially on date 21 and 22. I don't have any idea how to solve this. 

-0.20422681611111113,
    -0.20089513916666668,
    -0.19742714583333332,
    -0.1938270997222222,
    -0.1900995672222222,
    -0.18624945333333331,
    -0.18228201527777776,
    -0.17820285083333331,
    -0.17401786388888887,
    -0.16973321,
    -0.16535522805555555,
    -0.16089037277777776,
    -0.1563451511111111,
    -0.15172607277777778,
    -0.14703961833333334,
    -0.1422922213888889,
    -0.13749026444444445,
    -0.13264007944444445,
    -0.12774794666666667,
    23.877179913333332, 21-March-2025
    23.882137360277778, 22-March-2025
    -0.11288163333333334,
    -0.10788293972222222,
    -0.10287223000000001,
    -0.09785493611111111,
    -0.09283622333333333,
    -0.08782098527777778,
    -0.08281385944444444,
    -0.0778192661111111,
    -0.07284146555555555

    -0.20339463916666667,
    -0.20000534833333333,
    -0.19648880444444444,
    -0.1928504375,
    -0.18909550277777776,
    -0.18522903888888886,
    -0.18125585277777778,
    -0.17718053138888887,
    -0.17300748944444444,
    -0.16874104055555555,
    -0.16438548194444444,
    -0.15994518138888889,
    -0.15542465444444445,
    -0.1508286261111111,
    -0.14616207416666666,
    -0.14143025083333333,
    -0.13663867944444444,
    -0.1317931311111111,
    -0.1268995825,
    23.878035835555558, 21-March-2024
    23.883006888055554, 22-March-2024
    -0.11199271916666667,
    -0.10696931027777778,
    -0.10192922083333333,
    -0.09687879166666666,
    -0.09182436805555555,
    -0.0867722975,
    -0.08172891916666666,
    -0.07670054222222222,
    -0.07169340555555556
	
	-0.20590069111111112,
    -0.20261422083333336,
    -0.19918840305555555,
    -0.19562896916666667,
    -0.19194177638888887,
    -0.18813280166666665,
    -0.18420814472222222,
    -0.18017402555555553,
    -0.1760367747222222,
    -0.17180280805555553,
    -0.1674785822222222,
    -0.16307053722222223,
    -0.15858502277777778,
    -0.15402822638888888,
    -0.14940610583333333,
    -0.1447243388888889,
    -0.13998829944444444,
    -0.1352030661111111,
    -0.13037345833333333,
    -0.12550410083333333,
    23.87940050027778, 21-March-2023
    23.88433587361111, 22-March-2023
    -0.11070249333333335,
    -0.10571922027777779,
    -0.10071908083333334,
    -0.0957070286111111,
    -0.09068820222222222,
    -0.08566790861111111,
    -0.08065159555555555,
    -0.0756448175

**Comment by WimDeMeester** [comment]
There were indeed a few problems with the calculation of the equation of time.  I think I have fixed them.  The problems were:
- CarbonInterval does not allow to create negative intervals.  So I return a float now.  
- The value of 23.87... was not correct.  It was 24 hours too much.  This is also solved.

Can you test the new version (6.2)?  

Can you also let me know which project you are working on?  I'm just interested :P
